# Utiliser une image Python officielle comme base
FROM python:3.11-alpine

# Installer le client PostgreSQL
RUN apk add --no-cache postgresql-client

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le contenu actuel du répertoire vers le répertoire /app dans le conteneur
COPY . .

# #variables d'environnement
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD soriya
ENV DB_HOST soriyab16-mateo.francecentral.azurecontainer.io

# Installer les dépendances de l'application
RUN pip install psycopg2-binary meteofrance_api

# Définir la commande à exécuter lors du démarrage du conteneur
CMD ["python", "main.py"]